### ISSUE TITLE
Latest or next meeting URI

### ISSUE THREAD

**Issue by iadawn** [w3c/calendar#122]
Hi,

Would be good to have series URI that is consistent which points to the next meeting.

For example:

https://www.w3.org/events/meetings/fad52978-dc63-4427-90b9-e64dd31b0566/20240611T110000/ - links to the meeting on 11 Jun

Could also have:

https://www.w3.org/events/meetings/fad52978-dc63-4427-90b9-e64dd31b0566/next - which also links to the meeting on 11 Jun if the current date is prior to the 11 Jun and subsequent to the date of the previous meeting.

This would make it extremely easy for people to bookmark a weekly event without the need for checking the relevant date.

Kevin

**Comment by rachaelbradley** [comment]
From AG: The calendar does not always work well with other calendars and some members find the calendar meeting emails difficult to locate or understand. For this and other reasons, some members need to create custom solutions for tracking their meetings. In order to do this, they need a stable URI to point to that includes the meeting name, time of day, meeting link and phone numbers (essentially the information on the current PHP pages). This information should be behind a sign in to restrict it.  We need this before the PHP pages retire.

**Comment by daniel-montalvo** [comment]
Relates to #109

**Comment by jean-gui** [comment]
Instead of redirecting the event series https://www.w3.org/events/meetings/fad52978-dc63-4427-90b9-e64dd31b0566/ to its first event, this page now displays an overview, containing the next event, a few upcoming and past ones, with links to full lists. That page is also linked from specific events, see the "Overview of the recurring event" link of https://www.w3.org/events/meetings/fad52978-dc63-4427-90b9-e64dd31b0566/20241119T110000/ for example.

I believe this resolves the issue.

**Comment by daniel-montalvo** [comment]
Thank you very much @jean-gui for putting these pages together.
These are going to be of huge help for people who want a stable URL for a recurring meeting.
