### ISSUE TITLE
link goes to wrong meeting

### ISSUE THREAD

**Issue by jnurthen** [w3c/calendar#31]
I have a calendar invite for an event (meeting 25-Mar-21)
https://lists.w3.org/Archives/Public/public-aria/2021Mar/0026.html

The link View this event in your browser goes to the meeting invite from 18-Mar-21

Previously logged as #29 - was closed and I cannot reopen

**Comment by jean-gui** [comment]
Sorry about that, I should have been more specific in my reply in #29.

The link, as it didn't contain a reference to a specific occurrence, redirects to the first one (2021-03-18).
The bug is fixed as this link in future emails will now contain a reference to the correct occurrence. But unfortunately I cannot fix emails that have already been sent.

Does that make sense?

**Comment by jnurthen** [comment]
So how do I resolve this and send a new email to my group to fix all of their calendar instances?

**Comment by jean-gui** [comment]
Good question. Because we don't (yet?) have a way to force sending these emails, the only way to go is to change a property such as location, joining instructions or dates. But if you then want to revert the change, a second email will then be sent, which is also problematic.

I believe I should be able to force notifs to be resent only once as I have access to the backend server. Are you ok with me doing it?

**Comment by jnurthen** [comment]
Yes please

**Comment by jean-gui** [comment]
Done, see https://lists.w3.org/Archives/Public/public-aria/2021Mar/0027.html. The subject of the email is a bit different, I hope that's not an issue.
