### ISSUE TITLE
Join link and accessibility?

### ISSUE THREAD

**Issue by plehegar** [w3c/calendar#49]
When looking at an event, the formatting of the event itself is hard to understand, the join link is almost invisible due to contrast issues, and several members of my WG who use screen readers have mentioned difficulty with finding the join link in the email. 

from @wareid

**Comment by plehegar** [comment]
The current color contrast for the colors 1A5E9A and E9ECEF is 5.69:1 (required is [4.5:1](https://www.w3.org/TR/2021/WD-WCAG22-20210521/#contrast-minimum)), so we're within the level AA required by WCAG 2.1. Nevertheless, we can certainly increase the contrasts to go higher (we can use [Color Contrast Accessibility Validator](https://color.a11y.com/Contrast/).

fyi @michael-n-cooper

**Comment by jean-gui** [comment]
Looking at the following screenshot, it seems that Outlook doesn't interpret the HTML/CSS properly, thus resulting in the unreadable join link. I am not sure how to fix it yet, but will think about it.

Regarding the position of the link, we have changed it recently to be in the "Joining Instructions" section.

![Screen Shot 2021-07-13 at 9 53 32 AM](https://user-images.githubusercontent.com/1479073/125799685-18ebc7bb-98fc-481b-9035-32cf0e77731c.png)

**Comment by jean-gui** [comment]
I have completely changed the way these emails are generated a few weeks ago and they should now look better and shouldn't have this contrast issue anymore.
Note that as far as I can tell this was only happening with Outlook on Windows because its handling of HTML emails is very bad. That's also for this reason that these emails don't look great, while on any other clients I have tested it on, the email looks exactly as the version on the Web.
