### ISSUE TITLE
Delete events

### ISSUE THREAD

**Issue by plehegar** [w3c/calendar#51]
It's not really possible to "cancel" a calendar event, they still appear in the calendar and don't seem to get removed from calendars.

via @wareid

This is true once an event is tentative or confirmed.

**Comment by jean-gui** [comment]
When canceling a tentative or confirmed event, if you choose to send notifications (recent change, before the notification was always sent), the email contains an attached ics file. Most calendar clients are supposed to then show you a button to update your calendar, but this may not be the case with Outlook (see possibly related #47).

@wareid Did you receive such an email after canceling the event?

**Comment by shawna-slh** [comment]
To remove a cancelled event, you need to send a request to sysreq@w3.org per Jean-Gui "This could only be done by the systems team in the main database."

**Comment by jean-gui** [comment]
It is now possible to delete one-time events and event series or part of event series. There is a button at the bottom of the edit page that leads to the deletion form.
Note that it's still not possible to delete a single event that's part of an event series because it's more difficult to implement.
